// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBvwYwJKic940DAh7tvljUjXuxHLF3pI',
    appId: '1:387463215998:web:8acc2a5da600b82160912f',
    messagingSenderId: '387463215998',
    projectId: 'mobprogfbasecrud',
    authDomain: 'mobprogfbasecrud.firebaseapp.com',
    storageBucket: 'mobprogfbasecrud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqKthFd0znVEiOIDNf0DFwPDD-mFsTimM',
    appId: '1:387463215998:android:f9f4d1619b1ff0c260912f',
    messagingSenderId: '387463215998',
    projectId: 'mobprogfbasecrud',
    storageBucket: 'mobprogfbasecrud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNlbV8AQ-5MYFHkXof6gDFuU_vnDIpRo8',
    appId: '1:387463215998:ios:5dc5bc4e2fe33b6e60912f',
    messagingSenderId: '387463215998',
    projectId: 'mobprogfbasecrud',
    storageBucket: 'mobprogfbasecrud.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNlbV8AQ-5MYFHkXof6gDFuU_vnDIpRo8',
    appId: '1:387463215998:ios:5dc5bc4e2fe33b6e60912f',
    messagingSenderId: '387463215998',
    projectId: 'mobprogfbasecrud',
    storageBucket: 'mobprogfbasecrud.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJBvwYwJKic940DAh7tvljUjXuxHLF3pI',
    appId: '1:387463215998:web:a31a6037452bf94d60912f',
    messagingSenderId: '387463215998',
    projectId: 'mobprogfbasecrud',
    authDomain: 'mobprogfbasecrud.firebaseapp.com',
    storageBucket: 'mobprogfbasecrud.firebasestorage.app',
  );
}
